name: GPIO Emergency to MQTT
version: "0.1.4"
slug: acb61124_gpio_emergency
arch:
  - aarch64
  - armv7
  - armhf
host_network: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/gpiomem
options:
  gpio_pin: 17
  mqtt_host: core-mosquitto
schema:
  gpio_pin: int
  mqtt_host: str
