name: GPIO Emergency to MQTT
slug: acb61124_gpio_emergency
version: "0.1.6"           # tăng version để buộc HA rebuild
description: Read Raspberry Pi GPIO and publish to MQTT for emergency button.
url: https://github.com/hiendz0511-dev/Teemo/tree/main/gpio_emergency

arch:
  - aarch64
  - armv7
  - armhf

init: true                 # dùng s6 (bắt buộc với services.d)
host_network: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/gpiomem

options:
  gpio_pin: 17
  mqtt_host: core-mosquitto

schema:
  gpio_pin: int
  mqtt_host: str
