name: GPIO Emergency to MQTT
slug: gpio_emergency
version: "0.1.2"
description: Read Raspberry Pi GPIO and publish to MQTT for emergency button
startup: services
arch: [aarch64, armv7, armhf]
host_network: true
privileged: [SYS_RAWIO]
devices: ["/dev/gpiomem"]
options:
  gpio_pin: 17
  mqtt_host: core-mosquitto
schema:
  gpio_pin: int
  mqtt_host: str
